//! Embed `web/dist` into the binary at compile time (ADR 006).
//!
//! Emits `embedded_assets.rs` into `OUT_DIR`. When `web/dist` does not exist
//! (fresh clone, `cargo test` before `npm run build`), a placeholder
//! `index.html` is embedded instead so the workspace always builds.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-changed=../../web/dist");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let dist = manifest_dir.join("..").join("..").join("web").join("dist");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    if dist.is_dir() {
        collect(&dist, &dist, &mut entries);
    }
    if !entries.iter().any(|(rel, _)| rel == "index.html") {
        entries.push((
            "index.html".to_owned(),
            manifest_dir.join("assets").join("fallback_index.html"),
        ));
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut code = String::from(
        "// @generated by build.rs - do not edit\npub static ASSETS: &[(&str, &[u8])] = &[\n",
    );
    for (rel, abs) in &entries {
        let abs = abs.to_string_lossy().replace('\\', "/");
        code.push_str(&format!("    ({rel:?}, include_bytes!({abs:?})),\n"));
    }
    code.push_str("];\n");

    fs::write(out_dir.join("embedded_assets.rs"), code).expect("write embedded_assets.rs");
}

fn collect(root: &Path, dir: &Path, entries: &mut Vec<(String, PathBuf)>) {
    let Ok(read) = fs::read_dir(dir) else { return };
    for entry in read.flatten() {
        let p = entry.path();
        if p.is_dir() {
            collect(root, &p, entries);
        } else if let Ok(rel) = p.strip_prefix(root) {
            entries.push((rel.to_string_lossy().replace('\\', "/"), p));
        }
    }
}
