[package]
name = "orbynode-daemon"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "orbynode"
path = "src/main.rs"

[dependencies]
axum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
orbynode-api = { workspace = true }
orbynode-core = { workspace = true }
orbynode-terminal = { workspace = true }
